"""add system settings table

Revision ID: 9d4098c9e842
Revises: fc44b9873afb
Create Date: 2026-09-14 11:20:24.238635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d4098c9e842'
down_revision: Union[str, None] = 'fc44b9873afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=20), nullable=True),
    sa.Column('embedding_provider', sa.String(length=20), nullable=True),
    sa.Column('ocr_provider', sa.String(length=20), nullable=True),
    sa.Column('openai_api_keys_encrypted', sa.Text(), nullable=True),
    sa.Column('openai_model', sa.String(length=100), nullable=True),
    sa.Column('gemini_api_keys_encrypted', sa.Text(), nullable=True),
    sa.Column('gemini_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('gemini_embedding_model', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
