"""add job posting and candidate profile fields (level, salary, portfolio, specialty)

Revision ID: a1b2c3d4e5f6
Revises: 9d4098c9e842
Create Date: 2026-09-21 00:00:00.000000

Hand-written (not autogenerated) — see DEVELOPMENT.md if you're reading this
wondering why; the environment's disk was temporarily full when this was
authored, so `alembic revision --autogenerate` couldn't be run against a
live DB. Verify with `alembic upgrade head` before relying on it, same as
any migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "9d4098c9e842"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SENIORITY_LEVEL = postgresql.ENUM(
    "INTERN", "FRESHER", "JUNIOR", "MID", "SENIOR", "LEAD", "MANAGER", "DIRECTOR",
    name="seniority_level",
)
SALARY_CURRENCY = postgresql.ENUM("VND", "USD", name="salary_currency")
GENDER_REQUIREMENT = postgresql.ENUM("ANY", "MALE", "FEMALE", name="gender_requirement")


def upgrade() -> None:
    bind = op.get_bind()
    SENIORITY_LEVEL.create(bind, checkfirst=True)
    SALARY_CURRENCY.create(bind, checkfirst=True)
    GENDER_REQUIREMENT.create(bind, checkfirst=True)

    # --- jobs ---------------------------------------------------------------
    op.add_column("jobs", sa.Column("level", postgresql.ENUM(name="seniority_level", create_type=False), nullable=True))
    op.add_column("jobs", sa.Column("salary_min", sa.Numeric(14, 2), nullable=True))
    op.add_column("jobs", sa.Column("salary_max", sa.Numeric(14, 2), nullable=True))
    op.add_column(
        "jobs",
        sa.Column("salary_currency", postgresql.ENUM(name="salary_currency", create_type=False), nullable=False, server_default="VND"),
    )
    op.add_column(
        "jobs",
        sa.Column("salary_negotiable", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("jobs", sa.Column("working_hours", sa.String(length=255), nullable=True))
    op.add_column("jobs", sa.Column("benefits", sa.Text(), nullable=True))
    op.add_column("jobs", sa.Column("hiring_reason", sa.Text(), nullable=True))
    op.add_column("jobs", sa.Column("age_min", sa.Integer(), nullable=True))
    op.add_column("jobs", sa.Column("age_max", sa.Integer(), nullable=True))
    op.add_column(
        "jobs",
        sa.Column("gender_requirement", postgresql.ENUM(name="gender_requirement", create_type=False), nullable=False, server_default="ANY"),
    )
    op.add_column("jobs", sa.Column("technical_skills", sa.Text(), nullable=True))
    op.add_column("jobs", sa.Column("soft_skills", sa.Text(), nullable=True))
    # Drop the server defaults once existing rows are backfilled — new rows
    # get their default from the ORM/schema layer instead (see models/job.py),
    # same pattern used by the extraction_method migration.
    op.alter_column("jobs", "salary_currency", server_default=None)
    op.alter_column("jobs", "salary_negotiable", server_default=None)
    op.alter_column("jobs", "gender_requirement", server_default=None)

    # --- candidates -----------------------------------------------------------
    op.add_column("candidates", sa.Column("portfolio_url", sa.String(length=500), nullable=True))
    op.add_column(
        "candidates",
        sa.Column("current_level", postgresql.ENUM(name="seniority_level", create_type=False), nullable=True),
    )
    op.add_column("candidates", sa.Column("primary_specialty", sa.String(length=100), nullable=True))
    op.add_column("candidates", sa.Column("expected_salary_min", sa.Numeric(14, 2), nullable=True))
    op.add_column("candidates", sa.Column("expected_salary_max", sa.Numeric(14, 2), nullable=True))
    op.add_column(
        "candidates",
        sa.Column(
            "expected_salary_currency",
            postgresql.ENUM(name="salary_currency", create_type=False),
            nullable=False,
            server_default="VND",
        ),
    )
    op.alter_column("candidates", "expected_salary_currency", server_default=None)


def downgrade() -> None:
    op.drop_column("candidates", "expected_salary_currency")
    op.drop_column("candidates", "expected_salary_max")
    op.drop_column("candidates", "expected_salary_min")
    op.drop_column("candidates", "primary_specialty")
    op.drop_column("candidates", "current_level")
    op.drop_column("candidates", "portfolio_url")

    op.drop_column("jobs", "soft_skills")
    op.drop_column("jobs", "technical_skills")
    op.drop_column("jobs", "gender_requirement")
    op.drop_column("jobs", "age_max")
    op.drop_column("jobs", "age_min")
    op.drop_column("jobs", "hiring_reason")
    op.drop_column("jobs", "benefits")
    op.drop_column("jobs", "working_hours")
    op.drop_column("jobs", "salary_negotiable")
    op.drop_column("jobs", "salary_currency")
    op.drop_column("jobs", "salary_max")
    op.drop_column("jobs", "salary_min")
    op.drop_column("jobs", "level")

    bind = op.get_bind()
    GENDER_REQUIREMENT.drop(bind, checkfirst=True)
    SALARY_CURRENCY.drop(bind, checkfirst=True)
    SENIORITY_LEVEL.drop(bind, checkfirst=True)
