"""add cv extraction method

Revision ID: fc44b9873afb
Revises: b356a2a2ab6c
Create Date: 2026-09-14 06:43:25.678829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc44b9873afb'
down_revision: Union[str, None] = 'b356a2a2ab6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'candidate_cvs',
        sa.Column('extraction_method', sa.String(length=20), nullable=False, server_default='text'),
    )
    op.alter_column('candidate_cvs', 'extraction_method', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_cvs', 'extraction_method')
    # ### end Alembic commands ###
